### ISSUE TITLE
Create a Desktop and Mobile App (Using Electron?)

### ISSUE THREAD

**Issue by artforlife** [zen-audio-player/zen-audio-player.github.io#224]
Is this in the plans? Or has this been done? Perhaps Electron can be used.

**Comment by shakeelmohamed** [comment]
I've thought about this, but haven't gotten around to it. Are you interested in starting work on it? I can make a separate repo

**Comment by artforlife** [comment]
I am interested. Would we need to fork or do pull requests?

**Comment by shakeelmohamed** [comment]
Fork + pull request, I've made the repo at [zen-audio-player/app-electron](https://github.com/zen-audio-player/app-electron). I left some notes for you in https://github.com/zen-audio-player/app-electron/issues/1 - feel free to create issue on that repo to start tracking your work

Thanks for taking this on, closing this issue since we have a dedicated place for it now.
