### ISSUE TITLE
Functionality is totally broken

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#321]
I'm not sure exactly what's happened, but I think YouTube has made some API changes around CORS with the player widget.

TODO:
- [ ] Investigate & repurpose this issue

**Comment by andy-shi88** [comment]
At first, I thought this was caused by the `autoplay policy changes` issue, and later I found that in the `"ready"` flag, it's not showing the player.
Tried calling the `show` function and it works.

I'm not sure about the whole flow of this app, but is this the flow?
```
open link
auto play -> true
"playing" -> that.show() 
```
if this is it, then might be the autoplay policy update.
I'd be happy to work on this if it hasn't 
@shakeelmohamed

**Comment by andy-shi88** [comment]
just confirm, tried to allow `autoplay` permission in firefox and it works.
I think we'll need to comply with the new policy and call `show()` even it's not on `playing` yet.

**Comment by shakeelmohamed** [comment]
@andy-shi88 sounds great, please open a PR. You should be able to get it running locally w/ `npm start`

**Comment by andy-shi88** [comment]
PR opened @shakeelmohamed

**Comment by k----n** [comment]
I think this issue also depends on the browser.

In firefox, there is no such issue.
However in chrome there are issues with displaying the player and @andy-shi88 suggested changes fixes it.

**Comment by shakeelmohamed** [comment]
AFAIK this is "bug" no longer exists
