### ISSUE TITLE
Hyperlink video description contents

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#66]
If we add hyperlinks to any URLs in the video description the experience will be much better.

The links should follow the form: `<a href="http://example.com" target="_blank">` so the link opens in a new window/tab.

**Comment by eirism** [comment]
Hod do you think this should be implemented? I think regular expressions could be a way to do it. I think a problem with most ways to do it is to match all URLs in the description, because URLs can take so many forms (query strings, fragments, etc.)

((?:http|https)\:\/\/[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,3}(?:\/\S*[^\.\s\"])?) 
This RegEx matches too much, but I think it will be usable

**Comment by shakeelmohamed** [comment]
Hi @eirism,

I'm open to suggestions, my initial thought was regex but I have the similar doubts since URLs are so varied. If you're willing to do the work, we can start with a regex solution initially, then improve as we go.
